namespace AlbionDataAvalonia.Network.Models;

public enum AlbionMailInfoType
{
    UNKNOWN,
    MARKETPLACE_SELLORDER_FINISHED_SUMMARY,
    MARKETPLACE_BUYORDER_FINISHED_SUMMARY,
    MARKETPLACE_BUYORDER_EXPIRED_SUMMARY,
    MARKETPLACE_SELLORDER_EXPIRED_SUMMARY,
    BLACKMARKET_SELLORDER_EXPIRED_SUMMARY
}
