// <auto-generated />
using System;
using AlbionDataAvalonia.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbionDataAvalonia.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20260630172356_AddLegendaryItemAttunedToPlayerName")]
    partial class AddLegendaryItemAttunedToPlayerName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("AlbionDataAvalonia.Auth.Models.UserAuth", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserAuth");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Gathering.Models.GatheringCompletedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ActiveElapsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AlbionServerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SilverPerHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalEstimatedMarketValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EndedAtUtc");

                    b.ToTable("GatheringCompletedSessions");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Gathering.Models.GatheringCompletedSessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedMarketValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemUniqueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TotalEstimatedMarketValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("GatheringCompletedSessionItems");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Gathering.Models.GatheringUnfinishedSessionCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("GatheringUnfinishedSessionCheckpoints");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Legendary.Models.LegendaryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AlbionServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttunedToPlayerName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Attunement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContainerColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerIcon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ContainerObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrafterName")
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentDurability")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EstimatedMarketValue")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasItemDetails")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLegendaryDetails")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemUniqueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ObjectId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("PrivateContainerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SeenByPlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Strain")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAtUtc");

                    b.HasIndex("AlbionServerId", "ObjectId")
                        .IsUnique();

                    b.ToTable("LegendaryItems");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Legendary.Models.LegendaryItemTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LegendaryItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LegendaryItemId", "Position")
                        .IsUnique();

                    b.ToTable("LegendaryItemTraits");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Network.Models.AlbionMail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlbionServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuctionType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartialAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Received")
                        .HasColumnType("TEXT");

                    b.Property<double>("TaxesPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSilver")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalTaxes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitSilver")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TotalSilver");

                    b.HasIndex("AlbionServerId", "LocationId", "AuctionType", "Deleted", "Received");

                    b.ToTable("AlbionMails");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Network.Models.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AlbionServerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("QualityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawLocationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SalesTaxesPercent")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UnitSilver")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AlbionServerId", "LocationId", "Deleted", "DateTime");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Gathering.Models.GatheringCompletedSessionItem", b =>
                {
                    b.HasOne("AlbionDataAvalonia.Gathering.Models.GatheringCompletedSession", "Session")
                        .WithMany("Items")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Legendary.Models.LegendaryItemTrait", b =>
                {
                    b.HasOne("AlbionDataAvalonia.Legendary.Models.LegendaryItem", "LegendaryItem")
                        .WithMany("Traits")
                        .HasForeignKey("LegendaryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegendaryItem");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Gathering.Models.GatheringCompletedSession", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AlbionDataAvalonia.Legendary.Models.LegendaryItem", b =>
                {
                    b.Navigation("Traits");
                });
#pragma warning restore 612, 618
        }
    }
}
